name: Build Docker images

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the postgis Docker image
      run: docker build db --file Dockerfile --tag geodb-db:latest
    - name: Build the pyhton Docker image
      run: docker build app --file Dockerfile --tag geodb-app:latest
